### ISSUE TITLE
Trackpad

### ISSUE THREAD

**Issue by williambj1** [dggomes/asuszephyrus-m#2]
Hello, 
is your trackpad working properly and is it a ELAN 1404?
Thanks.

https://github.com/williambj1/Hacintosh-EFI-Asus-Zephyrus-S-GX531

**Comment by dggomes** [comment]
Hi William, unfortunately, I still didn't manage to make it to work. Yes, I
think it's 1404.

**Comment by kylergib** [comment]
Hi, so just wanted to let you know that I have the same laptop as you and was on Gitter along with williambj1 and we have a fix for the trackpad! I uploaded my DSDT and the fix is posted here. 

https://github.com/alexandred/VoodooI2C/issues/171
It does only work in polling mode as far as I am aware. 

[DSDT.aml.zip](https://github.com/dggomes/asuszephyrus-m/files/3104908/DSDT.aml.zip)

**Comment by dggomes** [comment]
That's great news. Thanks for the efforts and update. I'll try this
solution later this week.

**Comment by kylergib** [comment]
Also if you are on high Sierra, you cannot use my DSDT directly as it is made for Mojave and I have the nvdidia GPU disabled

**Comment by SpAMCAN** [comment]
Ooh, I'll have to check this out. The trackpad (and weird USB/bluetooth issues) are some of my last things to sort with my setup

**Comment by Akkil123** [comment]
Hello sir I installed Mojave in Dell latitude. series as touch pad is not working

**Comment by SpAMCAN** [comment]
This is not a Dell Latitude repository, it's for the Asus Zephyrus M. Apologies!
